#!/usr/bin/python
from distutils.core import setup
from setuptools import find_packages

setup(name='botocross',
      version='1.0.3',
      packages=find_packages(),
      scripts=[
        'scripts/authorize-securitygroups.py',
        'scripts/create-buckets.py',
        'scripts/create-images.py',
        'scripts/create-securitygroups.py',
        'scripts/create-snapshots.py',
        'scripts/create-stacks.py',
        'scripts/create-topics.py',
        'scripts/decode-logs.py',
        'scripts/delete-buckets.py',
        'scripts/delete-images.py',
        'scripts/delete-keypairs.py',
        'scripts/delete-keys.py',
        'scripts/delete-securitygroups.py',
        'scripts/delete-snapshots.py',
        'scripts/delete-stacks.py',
        'scripts/delete-topics.py',
        'scripts/describe-images.py',
        'scripts/describe-instances.py',
        'scripts/describe-regions.py',
        'scripts/describe-securitygroups.py',
        'scripts/describe-snapshots.py',
        'scripts/describe-stacks.py',
        'scripts/describe-tags.py',
        'scripts/describe-volumes.py',
        'scripts/import-keypairs.py',
        'scripts/read-buckets.py',
        'scripts/revoke-securitygroups.py',
        'scripts/subscribe-topics.py',
        'scripts/update-stacks.py',
        'scripts/upload-keys.py',
        'scripts/validate-credentials.py',
        'scripts/validate-template.py',
      ],
      license='LICENSE',
      install_requires=[
        "boto >= 2.6.0",
      ],
      )
